### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by febuiles** [sarcilav/heroku-bartender#4]
I started playing a bit with the design but got nowhere. Leaving it here: http://s3.amazonaws.com/heroin-uploads/tender.zip
 in case you want to do anything with it.

**Comment by sarcilav** [comment]
I'm getting access denied http://cl.ly/5k1m ;(

**Comment by febuiles** [comment]
Remove the extra spaces at the end (%20%20).

**Comment by sarcilav** [comment]
Thanks for the design =) you can see it in 0.4.0 version
